### ISSUE TITLE
ERROR - Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by wezzou1** [verlok/lazyload#259] opened 2018-10-01 08:24 UTC
Hi, thank you for a good plugin, I'm currently working on a new site and I'm would love to use lazy-load on my images, but I've got an error when I'm trying to build app.js, I got this message

**Using UglifyJSPlugin**

`Unexpected token: keyword (const) [../node_modules/vanilla-lazyload/dist/lazyload.es2015.js:1,0][app.bundle.js:105,0]`

I'm using `"vanilla-lazyload": "8.15.2",`

**My webpack.config.js**

```js
'use strict';

const path = require('path');
const webpack = require("webpack");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const UglifyJSPlugin = require('uglifyjs-webpack-plugin')
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");

module.exports = {
  context: path.resolve(__dirname, "src"),
  entry: './js/app.js',
  output: {
    filename: "app.bundle.js",
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        sourceMap: true
      }),
      new OptimizeCSSAssetsPlugin({
        cssProcessorPluginOptions: {
          preset: ['default', { discardComments: { removeAll: true } }],
        },       
      })
    ]
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ["@babel/preset-env"]
            }
          }
        ],
      },
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          { 
            loader: 'css-loader', 
            options: { 
              importLoaders: 1 
            }
          },
          {
            loader: 'sass-loader'
          }
        ],
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        loader: 'url-loader?limit=1000&name=[name]-[hash].[ext]'
      }
    ],
  },
  externals: {
      'TweenMax': 'TweenMax'
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "app.bundle.css"
    })
  ],
};
```

**Comment by wezzou1** [comment] 2018-10-01 08:36
I'm also tried to install `vanilla-lazyload@8.15.2` then I got

```
ERROR in app.bundle.js from UglifyJs
Unexpected token: punc ()) [../node_modules/vanilla-lazyload/dist/lazyload.es2015.js:1,0][app.bundle.js:105,26]
```

**Comment by verlok** [comment] 2018-10-01 08:52
Duplicate of #247

**Comment by verlok** [comment] 2018-10-01 08:57
I think the error is because uglify is trying to minify the `dist/lazyload.es2015.js` file which is written in ES6 and not transpiled to ES5. UglifyJS cannot minify ES6.

You could either:

* try [babel/minify](https://github.com/babel/minify) 
* make your webpack configuration to point at the `dist/lazyload.js`
* use the already minified file `dist/lazyload.min.js`

Let me know what solves for you.

**Comment by verlok** [comment] 2018-10-02 08:37
@wezzou1 any luck with one of my suggestions? Let us know here, it might be of help for others.

**Comment by wezzou1** [comment] 2018-10-02 09:07
@verlok I will test now, will return!

**Comment by wezzou1** [comment] 2018-10-02 12:49
@verlok Yes, it's working! I changed `import Lazyload from 'vanilla-lazyload'` to `import LazyLoad from 'vanilla-lazyload/dist/lazyload'` Thanks again for an awesome plugin!

**Closed** 2018-10-02 16:38 UTC
Labels: TYPE: Question
