### ISSUE TITLE
Callback load not firing with picture source loading

### ISSUE THREAD

**Issue by mateutek** [verlok/lazyload#120] opened 2017-08-16 09:38 UTC
* What is happening?
There is no callback when the srcset is loaded, but it is loading correctly in the network panel
* What is the expected behaviour?
To trigger the callback
* Which version of LazyLoad are you using?
Tested everything from 7.1.0 to 8.0.3
* Could you provide the HTML, CSS and JS code you use for your images?
```javascript
var lazyLazy = new LazyLoad({
                elements_selector: ".js-item",
                threshold:50,
                // When the .js-item div enters the viewport...
                callback_set: function(parent) {
                    var $parent = $(parent);
                    // ...instantiate a new LazyLoad on it
                    var oneLL = new LazyLoad({
                        container: parent,
                        elements_selector:'.js-lazyload',
                        data_srcset:'source',
                        'skip-invisible':false,
                        callback_set:function(img){
                            $parent.addClass('item--loading');
                        },
                        callback_load:function(img){
                            console.log(img);
                            if(img.naturalHeight && img.complete){
                                var $bgContainer = $parent.find('.js-inspiration-image');
                                $bgContainer.css({'background-image':'url('+img.getAttribute('src')+')'});
                                $parent.removeClass('item--loading').addClass('item--loaded item--visible');
                            }else{
                                me.grid.hide($parent[0],{instant:true,onFinish:function(){
                                    me._debug('There is problem with image: '+img.getAttribute('src')  + ' , so we hid it.');
                                }});
                            }
                        }
                    });
                    // Optionally push it in the lazyLoadInstances 
                    // array to keep track of the instances
                    lazyLoadInstances.push(oneLL);
                },
            });
```
Thank you.

**Comment by verlok** [comment] 2017-08-22 19:50
Ok, this code is more complex than I was expecting. 
For what it looks, you have more than one scrolling containers (.js-item), each scrolling container has more than one image (.js-lazyload) and you want that when each one is loaded, the image source is set in the parent's background. Correct?

**Comment by verlok** [comment] 2017-08-22 19:55
I have some objections here: 
1) did you know that LazyLoad also works with `div` and tags different than `img`? In case you instantiate a LazyLoad with `elements_selector` pointing to those elements, it will load the images as background images, automatically 

2) you are reading the `src` attribute of an image, but you seem to set only the `srcset`. I would need to see the HTML code too. 

Anyway, this is complex to explain by writing in this conversation. Could you create a Pen on CodePen so I can see both HTML, CSS and JS code, and also fork it to fix the problem?

**Comment by verlok** [comment] 2017-08-23 06:39
Or at least report the HTML code of the pictures and their containers

**Comment by mateutek** [comment] 2017-08-23 08:14
Here is Html code.

I knew that when using it on div you can set the background, but will it work with `<picture>`?

I have n-number of this containers with only 1 image inside

```html
<div class="item js-item item--medium">
    <div class="item-content">
        <div class="inspiration">
            <div class="inspiration__content">
                <ul class="inspiration__tags">
                    <li class="tag">tag-01</li>
                    <li class="tag">tag-02</li>
                </ul>
                <div class="inspiration__title">inspiration-04</div>
            </div>
            <div class="inspiration__image js-inspiration-image">
                <picture>
                    <source media="(min-width: 1280px)" data-source="https://unsplash.it/427 427w">
                    <source media="(min-width: 1024px)" data-source="https://unsplash.it/341 341w">
                    <source media="(min-width: 992px)" data-source="https://unsplash.it/331 331w">
                    <source media="(min-width: 768px)" data-source="https://unsplash.it/256 256w">
                    <source media="(min-width: 568px)" data-source="https://unsplash.it/667 667w">
                    <source media="(min-width: 320px)" data-source="https://unsplash.it/375 375w">
                    <source data-source="https://unsplash.it/320">
                    <img class="js-lazyload" data-original="https://unsplash.it/427"> 
                </picture>
            </div>
        </div>
    </div>
</div>
```

**Comment by verlok** [comment] 2017-08-28 15:40
Sorry about the delay, I'll check as soon as possible.

**Comment by verlok** [comment] 2017-08-30 21:16
Ok so first things first: your `picture` markup has some errors, since in the `data-source` attribute you need to put the source without the width descriptor (`w`). The correct code would be the following. [DEMO here](https://codepen.io/verlok/pen/XaoNVE?editors=1000)

```html
<picture>
    <source media="(min-width: 1280px)" srcset="https://unsplash.it/427">
    <source media="(min-width: 1024px)" srcset="https://unsplash.it/341">
    <source media="(min-width: 992px)" srcset="https://unsplash.it/331">
    <source media="(min-width: 768px)" srcset="https://unsplash.it/256">
    <source media="(min-width: 568px)" srcset="https://unsplash.it/667">
    <source media="(min-width: 320px)" srcset="https://unsplash.it/375">
    <source data-source="https://unsplash.it/320">
    <img class="js-lazyload" data-original="https://unsplash.it/427">
</picture>
```

**Comment by verlok** [comment] 2017-08-30 21:31
Secondly, if I understand correctly, you're trying to use a hidden `picture` tag in order to lazily load a responsive image, then when the load callback is fired, read which image was loaded, and place it in the `background-image` of the parent `.js-inspiration-image` element. Right?

The main problem I see here is in the following line, since the `src` attribute of the `img` doesn't change when the image is loaded, it remains the one in the markup. [DEMO here](https://codepen.io/verlok/pen/XaoNVE?editors=1010) (open browser console).

```js
$bgContainer.css({'background-image':'url('+img.getAttribute('src')+')'});
```

**Comment by verlok** [comment] 2017-08-30 22:15
...BUT you could change that line of code like the following, and it would work... on browser supporting the currentSrc property, meaning that it won't work on IE 11.

```js
$bgContainer.css({'background-image':'url('+img.currentSrc+')'});
```

It should work, I'd just feel very dirty if I did the thing your trying to do. :)
Can I ask why aren't you using the `img` in `position: absolute` with a lower `z-index` instead of using `background-image`?

**Comment by verlok** [comment] 2017-08-30 22:19
Also please note that the javascript code you reported in the first post is very long and complex even for what you're trying to do, you're instantiating multiple `LazyLoad`s when you really need only one.

**Comment by verlok** [comment] 2017-08-30 23:02
Closing this because it's not a bug, but let's continue the discussion if you like

**Closed by verlok** 2017-08-30 23:02 UTC
Labels: help wanted
