### ISSUE TITLE
MS Edge supported?

### ISSUE THREAD

**Issue by chrisjansky** [verlok/lazyload#135] opened 2017-09-16 08:06 UTC
Using the latest version (10.3.0) I can't get lazyload to work in MS Edge 15 (latest version). Is it supported and/or are there any special steps to make it work?

```
var loadImages = new LazyLoad({
  elements_selector: "[data-src]"
});
```
and
```
<div class="m-split__image" data-src="src/static/img/work/kocianka-6.jpg"></div>
```

URL: http://www.via-electra.eu/2017/

Thanks!

**Comment by verlok** [comment] 2017-09-18 12:57
It's supposed to work, but I can't tell tell you for sure now, since I'm away from my Windows machine until the 26th. Is it working in other browsers?

**Comment by verlok** [comment] 2017-09-18 13:02
Could you report any error you receive in the browser console (F12 to open it on Edge)?

Is version 8 working on Edge? You could stick to that until I fix version 10 :)

**Comment by chrisjansky** [comment] 2017-09-19 07:52
Hello Andrea,
yes, it is working OK in Chrome and Safari. The funny thing is I don't seem to be getting any errors with 10.3.0:
![screen shot 2017-09-19 at 09 48 58](https://user-images.githubusercontent.com/5342612/30581319-014aa086-9d20-11e7-8361-31b630b8e2aa.png)

I'll try version 8 again, but I didn't have any luck with that before either.

**Comment by verlok** [comment] 2017-09-19 08:16
Thanks for the report.

If neither 10 nor 8 work on Edge, maybe the problem is related to the HTML errors that I see in your browser console?
It says that you're using a self closing tag and it can't be, that you should close it. Which tags is it referring to?

Please report your HTML and JS code here, that could help me to help you. :)

**Comment by liepumartins** [comment] 2017-09-19 09:22
I can confirm, that 10.3.0 did not work in Edge for me as well. No errors in console shown.
Now using 8.2.0, after setting `{data_src: 'src'}` it works.

Thank you!

**Comment by chrisjansky** [comment] 2017-09-19 21:07
Happy to confirm reverting to 8.2.0 and setting `data_src: 'src'` does the trick! I tried 8.2.0 before, but the `data_src` is apparently the critical part.

Thanks @liepumartins for the tip!

**Comment by verlok** [comment] 2017-09-21 13:49
@chrisjansky, what @liepumartin wrote is correct because the default options object changed between version 8 and 10. Find the docs in the README file of release 8 downloading the zip file [here](https://github.com/verlok/lazyload/releases/tag/8.2.0)

**Comment by npdung** [comment] 2017-09-26 08:34
I replace 
```javascript
var onIntersection = function onIntersection(entries) {
    entries.forEach(function (entry) {
        if (!entry.isIntersecting) {
            return;
        }
        var element = entry.target;
        revealElement(element, settings);
        _this._observer.unobserve(element);
    });
    _this._elements = purgeElements(_this._elements);
};
```

by 

```javascript
var onIntersection = function onIntersection(entries) {
    entries.forEach(function (entry) {
        if (entry.isIntersecting !== null && entry.isIntersecting === false) {
            return;
        }
        var element = entry.target;
        revealElement(element, settings);
        _this._observer.unobserve(element);
    });
    _this._elements = purgeElements(_this._elements);
};
```

because when i debug on MS Edge "entry.isIntersecting" is null not boolean

**Comment by aliasltb** [comment] 2017-09-26 10:08
Coincidentially I had the same issue, but on Chrome 56 and lower and was searching for a solution right now. I tried the fix of npdung and this works! This is the correct answer on this issue.

**Comment by verlok** [comment] 2017-09-26 16:11
I cannot debug on Edge 15 because my network administrator doesn't allow the update yet, and on at home a use a Mac. I think it's time to install a VM :D

Could you explain better why the condition in the `if` statement, meaning `(!entry.isIntersecting)` is not working on Edge? If the problem is that `entry.isIntersecting` is `null` as you explained, shouldn't it work anyway, since `!null` evaluates as `true`?

Thanks

/cc @aliasltb @npdung

**Comment by verlok** [comment] 2017-09-26 17:06
I found the bug documentation: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12156111/

**Comment by verlok** [comment] 2017-09-26 17:43
Released 10.3.1

**Comment by verlok** [comment] 2017-09-26 17:47
@aliasltb @npdung let me know if version 10.3.1 works on MS Edge 15 please. Thanks

**Comment by npdung** [comment] 2017-09-26 19:07
@verlok thank for your update and bug documentation, it working.

**Comment by aliasltb** [comment] 2017-09-27 09:06
@verlok  I updated your plugin to 10.3.1, but for me the loading behaviour is strange. I used this on Chrome 57 and all images do load as expected. But when I use lazyload in an owl carousel, the upcoming slides don't load the images - at least not immediately. With the solution of @npdung I works perfectly everywhere.

**Comment by verlok** [comment] 2017-09-27 10:26
You shouldn't lazy load images in carousels except using the native features of the carousels itself, for example, I know that slick slider (slick.js) has a feature too lazy load images outside the visible ones. 

The solution that @npdung provided is working only because it immediately loads all the images on some browsers… but that's not lazy loading.

**Comment by npdung** [comment] 2017-09-27 12:57
@aliasltb  version 10.3.1 is work with owl carousel, on Chrome 61, MS Edge 15.

my product: https://tacavet.familala.com/

**Comment by adriandmitroca** [comment] 2017-10-30 21:43
Still not working on latest version of MS Edge.

**Comment by verlok** [comment] 2017-10-30 21:52
@adriandmitroca which version of LazyLoad are you using? The recommended (8.2.1) or the latest (10.3.3)? And what problem are you experiencing?

**Comment by adriandmitroca** [comment] 2017-10-30 21:57
I have tried basically all available versions - latest builds for 8, 9 and 10. None worked.

**Comment by verlok** [comment] 2017-10-30 22:00
Thanks. With "none worked" you are not helping me to help you. What kind of problem were you experiencing? Did you get any javascript errors? Could you post the HTML and JS code you used? Thanks

**Comment by adriandmitroca** [comment] 2017-10-31 10:13
Sorry @verlok, I didn't mean it. I was referring to previous comments.

What I did was pretty much basic setup with just `data-src` attributes on `img` and initialization `new LazyLoad()`.

It worked great on all browsers, including IE9 except Edge, where images do not load at all.

**Comment by verlok** [comment] 2017-10-31 12:51
Hi @adriandmitroca,
you should definitely stick with version 8.x and use `data-original` instead of `data-src`. 
In fact, the API was different in 8.2.x as stated in the m documentation provided in the README.md for that version (download the zip for version 8.x then read README.md). 

Let me know if this solves. 
Thanks!

**Comment by verlok** [comment] 2017-10-31 13:02
Sorry, the option name is still `data_src` but the default option value is `original` so the HTML attribute it’s looking for is `data-original`. 

Here the documentation: https://github.com/verlok/lazyload/blob/master/README_v8.md#api

Long story short, if you want to keep `data-src` in your HTML you just need to do:

```js
new LazyLoad({data_src: "src"});
```

**Comment by stefan-kern** [comment] 2018-01-08 15:59
on chrome version 65.0.3298.3 while scrolling through a page, lazyload elements can have both 
```entry.intersectionRatio: 0``` and ```isIntersecting: true```. this appears seemingly at random, i could not reproduce it consistently, other than reloading the page and scrolling until it happens.

due to the recent change (edge fix) to ```if (entry.intersectionRatio > 0)``` this can lead to the case where images do not get loaded on chrome. i had to revert to the old version ```if (entry.isIntersecting)```, although i did not check if the current version of edge (16) is affected still. either way, it could be worked around with an additional ```if (entry.isIntersecting === null)```.

**Comment by stefan-kern** [comment] 2018-01-10 18:08
After some further tests, edge version 15.15063 and higher did work with the old entry.isIntersecting, so it might be a good idea to revert the change?

**Comment by stefan-kern** [comment] 2018-01-10 18:10
In case you also want to do some testing, here is a collection of various edge vms: https://github.com/magnetikonline/linuxmicrosoftievirtualmachines

**Comment by verlok** [comment] 2018-01-17 22:06
Thank you @stefan-kern for the analysis, I'll try and fix this as soon as possible. Thanks.

**Comment by verlok** [comment] 2018-01-17 22:29
Latest comments by @stefan-kern are a duplicate of #165. Closing this.

**Closed by verlok** 2018-01-17 22:29 UTC
