### ISSUE TITLE
threshold not working

### ISSUE THREAD

**Issue by podrivo** [verlok/lazyload#178] opened 2018-02-07 03:25 UTC
* What is happening?
I'm not sure what is happening, but it seems the `threshold` is not working. Image is only triggered to load when it hits the user viewport.

* Which version of LazyLoad are you using?
10.4.2

* In which browser(s) and browser version(s) are you experiencing the problem?
Chrome 64

* Could you provide the HTML, CSS and JS code you use for your images?
https://codepen.io/podrivo/pen/EQgddV

* What are the steps to reproduce the problem?
Check console for logs that images are only set when it hits the viewport.

Do you know what it is I'm doing wrong?
Thank you.

**Comment by verlok** [comment] 2018-02-07 21:39
Hi @podrivo,
I've tried the Pen you provided on Chrome 64 on Mac, and I didn't notice any particular problem.

I suggest you to add a minimum height to the images, otherwise they would be 0 pixel and be shown all at the same time. I did it on [this fork](https://codepen.io/verlok/pen/wyoyoq) of your Pen setting a `min-height` on the images, but the best way to do it would be the one I described in the section [occupy vertical space and maintain ratio](https://github.com/verlok/lazyload#occupy-vertical-space-and-maintain-ratio) of the readme. If you don't feel like using the padding trick, you could also use [a combination of CSS grid and SVG](https://codeburst.io/keeping-aspect-ratio-with-html-and-no-padding-tricks-40705656808b).

Let me know if this solves.
Thanks

**Comment by podrivo** [comment] 2018-02-08 15:47
Hey @verlok, I'm aware of the minimum height to occupy vertical space, but the problem for me, is that the `callbacks` are ignoring the` threshold`.

I've made this video, to better illustrate my side: https://d2ffutrenqvap3.cloudfront.net/items/072O3N3L1v0y0Z273L1J/threshold.mp4

Same thing happens in the pen you forked.

**Comment by dnjstlr555** [comment] 2018-02-10 05:35
I'm having same problem.

**Comment by verlok** [comment] 2018-02-10 21:12
Duplicate of #176

**Closed by verlok** 2018-02-10 21:12 UTC
Labels: duplicate

**Comment by podrivo** [comment] 2018-02-10 21:25
Hey @verlok , this is not the same issue as https://github.com/verlok/lazyload/issues/176...
They're both regarding the use of callbacks and threshold, but they are separate issues.
