### ISSUE TITLE
Native image lazy-loading

### ISSUE THREAD

**Issue by szepeviktor** [verlok/lazyload#332] opened 2019-04-08 13:25 UTC
Are you planning to prepare detecting native lazy loading? https://addyosmani.com/blog/lazy-loading/

**Comment by verlok** [comment] 2019-04-08 14:08
Yes.

**Comment by verlok** [comment] 2019-04-08 14:08
Duplicate of #331

**Closed by verlok** 2019-04-08 14:08 UTC
Labels: TYPE: Enhancement

**Comment by szepeviktor** [comment] 2019-04-08 14:29
Thanks.
