### ISSUE TITLE
Loading images on refresh

### ISSUE THREAD

**Issue by vonPiernik** [verlok/lazyload#85] opened 2017-04-12 13:48 UTC
Hi! When I refresh the page the images are not loading until I scroll a bit up or down.  Have you any idea what could be causing this problem?
Regards

**Comment by verlok** [comment] 2017-04-13 05:45
Hello @vonPiernik,
thank you for reporting this issue. 

In order to be able to resolve this, I need more information in order to reproduce the bug.

* Which version of LazyLoad are you using?
* In which browser and browser version are you experiencing the problem?
* Could you provide the HTML, CSS and JS code you use for your images?
* What are the steps to reproduce the problem?

Please answer these questions, it'll really help me understand what's happening.
Thanks

**Comment by verlok** [comment] 2017-04-17 06:54
@vonPiernik you there? Are you still experiencing this issue?

**Comment by Niresh12495** [comment] 2017-04-17 11:35
`skip_invisible : false` will solve the issue.

**Comment by verlok** [comment] 2017-04-18 06:44
Thanks @niresh12495, but this is not the recommended solution. The skip_invisible option is there for another reason. I want to investigate and understand why this happens. Is that because the images are initially invisible?

**Comment by vonPiernik** [comment] 2017-04-18 07:08
Hi, sorry for the delay. I'm using `skip_invisible` because I have tabs with images, so this is only way to make this tabs working, aye?
My version of lazy is the latest version I think, downloaded maybe a week ago. Chrome 57.0.2987.133 (64-bit).
My code here: https://pastebin.com/wh6qn4G6
I know it's mess, combination of wordpress gallery and data tables and lightbox plugin ;D But it's a messy site. It's hard to reproduce the problem I think, now I know that my website could be a problem, but It's complicated :p

**Comment by Niresh12495** [comment] 2017-04-18 08:19
Ok i found out that http://azaliowe.pl this is your website, i have checked few image elements all the image are referenced to src not data-src
You are using lazyload wrong
Here is a website where you can check lazyloading of verlok
https://www.guest.blog/2427/benefits-of-drinking-alcohol/

**Comment by vonPiernik** [comment] 2017-04-18 08:25
I'm a bit stupid ;D This website must working so lazy is currently disabled and I give you code from living website, sorry for that. When I tried to use lazy the data-src was set up and it worked fine except when i refreshed without scrolling.

**Comment by verlok** [comment] 2017-04-22 07:18
Sorry for the delay. I'll check.

**Comment by verlok** [comment] 2017-04-22 07:24
@vonPiernik you reported only the HTML code in your previous comment. Can you also give me the JavaScript code that you're using, and more information about how you load the script (in the header, in the footer, with or without the `async` attribute)?
By the way, have you read the new recipes and guide I've created on the new [LazyLoad website](https://verlok.github.io/lazyload)?

**Comment by verlok** [comment] 2017-04-26 13:10
@vonPiernik I'm closing it , if you still experience the issue please provide more information

**Closed by verlok** 2017-04-26 13:10 UTC
