### ISSUE TITLE
W3C validation error: You can add 'data_sizes' in options

### ISSUE THREAD

**Issue by otr-tomek** [verlok/lazyload#95] opened 2017-05-12 15:42 UTC
W3C walidator: Error: The sizes attribute may be specified only if the srcset attribute is also present.

**Comment by verlok** [comment] 2017-05-12 21:08
Duplicate of #89

**Closed by verlok** 2017-05-12 21:08 UTC
Labels: duplicate

**Comment by verlok** [comment] 2017-07-06 20:30
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
