### ISSUE TITLE
srcset working

### ISSUE THREAD

**Issue by jd440** [verlok/lazyload#37] opened 2016-09-20 20:22 UTC
hi,

I'm looking to get responsive + lazyload by srcset so I'm very interest by your solution but…
I'm sorry to tell you that but are you sure http://verlok.github.io/lazyload/demos/with_srcset_sizes.html work?

When I'm testing it with Firefox Developer Tools > Responsive Design Mode doesn't matter the test resolution it always loading the ../img/[…]_15_a.jpg and never ../img/[…]_11_a.jpg what make me think srcset function is not working?

I test also with chrome

**Comment by verlok** [comment] 2016-09-21 02:18
Hello! Yes, I'm pretty sure it works, the thing is that browsers tend to use the image they have already downloaded (and stored in cache) instead of using a new one, so please repeat your test making sure you manually empty your browser cache :) Cheers

**Comment by verlok** [comment] 2016-09-21 02:18
PS: let me know if this solves

**Comment by jd440** [comment] 2016-09-21 04:47
thanks @verlok to have take time to reply to me
so I tried again with clear cache
it's ok w/ chrome

But on ff 44/windèws,  49/windows,  48/linux  it still loading the ../img/[…]_15_a.jpg

I also tried to add a meta viewport but it doesn't change anything

**Comment by verlok** [comment] 2016-09-21 05:27
Ok, it can depend also on the Retina display emulation of the browser. 

The point is: do you know what happens if lazy load is removed and the srcset is applied directly on the img tag? The answer is: exactly the same. So the problem is not in the lazy load. It depends on what purpose the demo is coded for. 

Also, please remember that srcset and sizes are useful to _suggest_ image dimensions to the browser, and its up tu it to choose what format to use, so the can be a difference between a browser and another. 

I'll close this issue since it's not related to my script.

**Closed by verlok** 2016-09-21 05:27 UTC

**Comment by jd440** [comment] 2016-09-21 07:06
After testing I found.

the problem come from the size attribut
sizes="220px"

**Comment by verlok** [comment] 2016-09-21 10:55
Ok, that attribute is perfectly acceptable if your images are always displayed at 220 css pixel wide.

In my example I just want the browser to select between the 220 wide image or the bigger one based on the display density (retina or not).

**Comment by verlok** [comment] 2016-09-21 11:12
Confused? I invite you to read [this guide](https://ericportis.com/posts/2014/srcset-sizes/)

**Comment by verlok** [comment] 2017-07-06 20:34
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
