### ISSUE TITLE
LazyLoad for Youtube videos and Google Maps

### ISSUE THREAD

**Issue by zhandosweb** [verlok/lazyload#407] opened 2019-12-27 02:09 UTC
Hello!

Please, let me ask one question. Can I use this script for LazyLoad Youtube videos and Google Maps?

**Comment by verlok** [comment] 2020-02-28 09:56
> Can I use this script for LazyLoad Youtube videos 

Yes.

> and Google Maps?

Yes.

It's not as easy as lazy loading images, but you can definitely do that.
Do you want me to explain how?

**Comment by zhandosweb** [comment] 2020-02-28 10:51
Thank you very much for the answer!

Oh sir, if you can show some code examples, that would be great! 🙏🙏🙏

In documentation with live code demos I didn't found, how to Lazy Load Youtube-videos and Google Maps. Maybe it will be interesting for other users too!

**Comment by verlok** [comment] 2020-02-28 14:19
Well, first of all, what kind of Google Map do you want to embed? 
If it's just an iframe with a Google Maps, that's quite easy...

```html
<iframe class="lazy" width="600" height="450" frameborder="0" style="border:0"
src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwewOctCkfDUR6-S1xnXZeho&key=..." allowfullscreen></iframe>
```

```js
new LazyLoad({ elements_selector: `.lazy`});
```

So I guess you want to do something more complex, right?

**Comment by verlok** [comment] 2020-02-28 14:21
And if you use iframes to embed Youtube videos too, it's simple as in the example above.

```html
<iframe class="lazy" width="560" height="315" src="https://www.youtube.com/embed/lJIrF4YjHfQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

```js
new LazyLoad({ elements_selector: `.lazy`});
```

**Comment by verlok** [comment] 2020-02-28 14:22
Does this answer your question?
If not, please show me the HTML + JS code you want to lazyload.

**Comment by verlok** [comment] 2020-03-05 06:12
Closing this. I assume this solved. 
Feel free to reopen if you still need advice.

**Closed by verlok** 2020-03-05 06:12 UTC
Labels: TYPE: Question

**Comment by hiddenman** [comment] 2020-04-11 22:35
Hi,

Sorry for reopening this question. Actually, we also need to lazyload youtube videos in iframes.
However,

1. If we set "src" as "data-src" (the same as we do for images), then it does not work
2. If we just add lazy class, what does it change?  Browser will fetch the URL on page load.
We just tested Google PageSpeed with iframes and it gave us very low score due to huge youtube scripts, delayed loading and so on.
I also see youtube requests during page load. And then lazyload loads them again!

So we definitely need the same behaviour with "data-src" for all kind of sources, don't we?  Why you use "src" for iframes, it won't work without it?

Thank you.

**Comment by verlok** [comment] 2020-04-11 22:44
You need to create a new LazyLoad instance with `elements_selector` pointing to your lazy iframes. 

E.g. 

HTML
`<iframe class=“lazy” data-src=“YouTube...”></iframe>`

JS
`new LazyLoad({ elements_selector: “.lazy”})`

**Comment by hiddenman** [comment] 2020-04-11 22:48
> You need to create a new LazyLoad instance with `elements_selector` pointing to your lazy iframes.
> 
> E.g.
> 
> HTML
> `<iframe class=“lazy” data-src=“YouTube...”></iframe>`
> 
> JS
> `new LazyLoad({ elements_selector: “.lazy”})`

Thank for quick reply, great :)  
Actually, i do have two  instances (code taken from another issue here), one global and second is for bootstrap modal:

 ```
 var globalLazyLoad = new LazyLoad({
        elements_selector: ".lazy"
        // ... more custom settings?
    });
```
```
   var modalLazyLoad;
    $('#mblock-10')
        .bind('shown.bs.modal', function () {
            modalLazyLoad = new LazyLoad({
                container: this
            });
        })
        .bind('hidden.bs.modal', function () {
            modalLazyLoad.destroy();
        });
```

So looks like i have to use another class, like lazyiframe and create something like:

`new LazyLoad({ elements_selector: “.lazy”})`

?

**Comment by hiddenman** [comment] 2020-04-11 22:52
Tried. Didn't help.

New instance and new class do not help, "data-src" is not loaded.
Setting it as "src" just loads iframes twice.

**Comment by verlok** [comment] 2020-04-11 22:52
The global LazyLoad already points to the lazy class elements, so it
should work in your case if you just add the lazy class to the iframes

**Comment by hiddenman** [comment] 2020-04-11 22:55
> The global LazyLoad already points to the lazy class elements, so it
> should work in your case if you just add the lazy class to the iframes and the data-src instead of src.

But it does not work with iframes inside bootstrap modal. Images are loaded, iframe src is not.
I can show you code or just point to the website/whatever.

So images work fine in modals. "iframes" do not. With just "src" they loaded twice - on page load by browser and on opening modal by lazyload.
With "data-src" they are not loaded at all.

**Comment by hiddenman** [comment] 2020-04-11 22:57
That's an example from the modal:

```
<div class="carousel-item">
 <div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item lazy" data-src="https://www.youtube.com/embed/3j1MU8AxECc" allowfullscreen></iframe>
 </div>
</div>
```

**Comment by hiddenman** [comment] 2020-04-11 23:03
vanilla-lazyload@15.1.1  if that matters.

**Comment by hiddenman** [comment] 2020-04-11 23:05
And here it how HTML looks when i open the modal. So it has some status "observed" and that's all:

`<iframe class="embed-responsive-item lazy" data-src="https://www.youtube.com/embed/3j1MU8AxECc" allowfullscreen="" data-ll-status="observed"></iframe>`

**Comment by hiddenman** [comment] 2020-04-11 23:31
You demo iframes.html work correctly with youtube. So i suppose this is related to the modal instance of the lazyload somehow.

**Comment by hiddenman** [comment] 2020-04-11 23:59
And here it the link to the original issue with code for modal:
https://github.com/verlok/lazyload/issues/50

So if you have any ideas why it does not work when we pass a container for the new instance, please let's try.

**Comment by hiddenman** [comment] 2020-04-12 12:00
It was hard to debug, but i found the root cause:

1. `queryElements()` never returns iframe objects of modals.
2. Here is the container (settings.container) data when we use Bootstrap modal: https://www.paste.org/104332
3. `settings.container.querySelectorAll(settings.elements_selector)` from function function `queryElements(settings)` never returns iframe objects from this container, only images
4. However, when i try directly `settings.container.querySelectorAll("iframe.lazy")`, it does return.
Not sure why `querySelectorAll()` ignores iframes here, will try to investigate.
May be you have an idea.

Thank you.

**Comment by hiddenman** [comment] 2020-04-12 12:07
Found that selector is 'img' when we pass modal to the new instance of Lazyload.
While in the main document selector is '.lazy', as in settings.

Not sure what and why changed it, though.

**Comment by hiddenman** [comment] 2020-04-12 12:30
Sorry, i'm stupid. Did so many unnecessary things, while i just had to add `elements_selector: ".lazy"` to the second instance of the Lazyload, because the default is `'img'`.

So everything is OK. Sorry :)
