### ISSUE TITLE
Lazyload with 100+ small images to load

### ISSUE THREAD

**Issue by baszero** [verlok/lazyload#49] opened 2017-01-24 14:48 UTC
I did an update. Can you check? I still lazyload is the issue, as the grid-layout is already implemented by left-floating `div`s. See #35

**Comment by verlok** [comment] 2017-01-24 19:40
Duplicate of #35

**Closed by verlok** 2017-01-24 19:40 UTC

**Comment by verlok** [comment] 2017-07-06 20:33
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
