### ISSUE TITLE
Use a loading image in "src"

### ISSUE THREAD

**Issue by Moon-Lover** [verlok/lazyload#217] opened 2018-06-28 12:35 UTC
Hello Verlok, and thank you for this very useful plugin!

I would like to ask you a question about **'placeholders'**!
I use lazyload on my site but with a **'placeholder'** in **'src'**, I know you do not recommend it, but I want to know if it only affects the loading time or if it has a negative effect on the SEO!?

If it's possible, I'd like to keep it that way! (**with a placeholder in the 'src' attribute**).
Thank you.

**Comment by verlok** [comment] 2018-06-28 15:00
Duplicate of #215

**Comment by verlok** [comment] 2018-06-28 15:02
Hello @moon-lover,
I’m still investigating on how lazy loading affects SEO, after they opened #215.

**Closed by verlok** 2018-06-28 15:02 UTC

**Comment by Moon-Lover** [comment] 2018-06-28 16:15
Thanks for the answer verlok!
