### ISSUE TITLE
Poorer performance if 100+ images are lazy loaded?

### ISSUE THREAD

**Issue by baszero** [verlok/lazyload#35] opened 2016-08-25 08:49 UTC
**Question**
I observe that when a page contains 100+ images that get loaded with lazyload the browser starts to stutter when scrolling down while more images are getting loaded.
Is this a known issue? Or what else could be the reason?

**Comment by verlok** [comment] 2016-08-25 09:39
Not a known issue. 
It could depend on many reasons, if you could link a page where this is developed and visitable, I can take a look at that and give you some advice. If you can't, please post some of your html, css and js code here.

**Comment by baszero** [comment] 2016-08-29 15:23
OK, I made our test environment public, but in order to see the effect, you have to login on the top right with stackoverflow / stackoverflow (un / pw).

When logged in, open this page which has about 130 lazy loaded thumbnail images.
If you scroll down, you will notice the stuttering.

http://test.zwischengas.com:8380/de/VC/veranstaltungsberichte/Grossglockner-Grand-Prix-2013-auf-den-Spuren-der-alten-Helden.html?gallery=on

Thanks for any advice.

**Comment by baszero** [comment] 2016-09-08 14:33
Any updates on this? I have to close the test environment otherwise soon again. Thanks for a quick note.

**Comment by verlok** [comment] 2016-09-08 15:29
Hi @baszero. For what I could see on your website, the problem is not due to LazyLoad but to the layout of the website. Try to avoid using HTML `table`s to layout the images, because it seems very CPU-consuming when a repaint occurs. 

I also notices that the Chrome/Opera inspector hangs/crashes when I tried to inspect an image. This must be due to a CPU issue. Try to use the "profile" tab in the inspector to find out where your problem is.

**Comment by baszero** [comment] 2016-09-09 09:09
Thanks for that quick analysis. I will change the layout. But if the performance issues are still there, I'll get back to you :) I will replace the `table` by left-aligned floating `div`s.

**Comment by baszero** [comment] 2017-01-24 14:23
Hi Verlok, you might want to look into this again, 
but I did use the PROFILE now and I see that lazyload is causing the delays!
See screenshot:
![screen shot 2017-01-24 at 15 22 54](https://cloud.githubusercontent.com/assets/596855/22250907/1de5c802-e249-11e6-8574-9c6178823a44.png)

**Comment by verlok** [comment] 2017-01-24 19:39
Good to know. I'll definitely check this out.

**Comment by verlok** [comment] 2017-01-24 19:43
Can you please make your test environment available again?

**Comment by verlok** [comment] 2017-01-24 22:26
Ok then, I've worked on it, used the profiler and found some performance issues, which I addressed and resolved in the latest version of LazyLoad, the recently released 4.0.2.
I also created a [demo with 320 images](http://verlok.github.io/lazyload/demos/hundreds.html) to test it and make sure that the performance issues are gone.

Please test it on your website and let me know if this can be closed again.

Important note: since version 4.0.0 the script only supports IE 10+.

**Comment by baszero** [comment] 2017-01-25 07:43
Ok, I will test it. However the IE10+ restriction is a big impact for us, have to decide whether we can use it.

Where do I see the version? In the `dist` folder there aren't any versions... Would be great to see version directories in the `dist` folder (e.g. v3.8, v3.9, v4.0 etc)

**Comment by baszero** [comment] 2017-01-25 07:51
Question: I will use the latest version in the `dist` folder, is that the latest too? Have they been updated with 4.0.2?

**Comment by verlok** [comment] 2017-01-25 08:48
Hi, I'm using GitHub's semantic versioning, so you can choose the version in the [releases page](https://github.com/verlok/lazyload/releases).
You're right, IE10+ can be a storng restriction in terms of backward compatibility, but it's now a standard not to support IE older than that. See [browser stats for november / december 2016 for desktop computers](http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201611-201612-bar).

**Comment by verlok** [comment] 2017-01-29 07:11
Can I close this @baszero?

**Closed** 2017-02-11 22:46 UTC

**Comment by verlok** [comment] 2017-07-06 20:34
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
