### ISSUE TITLE
Classes and Functions not working

### ISSUE THREAD

**Issue by Hackintosh** [verlok/lazyload#122] opened 2017-08-27 09:20 UTC
[Check out console output](http://jsbin.com/yumujiy/edit?html,console,output)

Only two classes and two call back functions are executed

**Comment by verlok** [comment] 2017-08-28 15:40
Thanks for letting me know, I'll check what happened

**Comment by Hackintosh** [comment] 2017-08-28 15:50
[Class error is also not being added in thise case](http://jsbin.com/xulamox/edit?html,console,output)

**Comment by verlok** [comment] 2017-08-28 21:39
I can't see what's triggering the error there. Can you explain?

By the way, have you checked the callbacks demo?
Code: https://github.com/verlok/lazyload/blob/master/demos/callbacks.html

**Comment by verlok** [comment] 2017-08-28 21:51
And [this is with the exact version (8.0.3)](https://codepen.io/verlok/pen/vJVzrb) you were using on jsfiddle.
It looks all good to me.

**Comment by Hackintosh** [comment] 2017-08-29 03:26
I have no idea, but this is a bug

**Comment by bitfella** [comment] 2017-08-30 19:08
Same here.
Css classes are not added, load callback is not triggered (but the script is working fine).
I am using latest npm package available (8.1.0), but I've tested 8.0.3 with the same result.

```
import LazyLoad from 'vanilla-lazyload';

const initLazyLoad = new LazyLoad({
  elements_selector: '.js-ll',
  class_loading: 'll-loading',
  class_loaded: 'll-loaded',
  class_error: 'll-error',
  callback_load: function (element) {
    console.log('image loaded');
  }
});
```

ES6 transpiled via Babbel, tested on Chrome 60.0.3112.90, Opera 47.0.2631.55, Safari 10.1 on Mac OS 10.11.6.

Any advice?

**Comment by verlok** [comment] 2017-08-30 21:03
@Hackintosh I managed to understand what's happening with your jsfiddle:

- **callback**: the option you are passing is `callback_procesed`, whereas the correct name of the option to pass is `callback_processed` (2 "s")
- **class**: the moment in which you print the `className` or your element is at page landing, not when the image loads, so you get the initial class names and not the changed one.

@bitfella:
- I'd need to see your HTML code too, to understand what you're doing. The best thing would be to have both HTML and JS code in a Pen on [Codepen](https://codepen.io/) so I could see what's happening.
- please note that the code in the `lazyload.js` and `lazyload.min.js` files is already ES5 code, so no need to transpile it with Babel.

**Comment by bitfella** [comment] 2017-08-30 21:46
Hello again,
I wrote 'ES6 transpiled via Babbel' just to point out that I am not embedding lazyload as a script in a page, but I am using it as an ES6 import in a Webpack bundle (transpiled with Babbel). I was guessing that maybe that was the problem.

Anyway, I just made a [codepen](https://codepen.io/anon/pen/Nvebmj) to show you the issue and it does not seem to work as well. 
Is there perhaps something I can't understand about how these features should work? Am I using the script in the wrong manner? In my intent it should append an 'll-loaded' class on each lazyloaded element, when the image has loaded fine. 

Thanks for your support!

**Comment by verlok** [comment] 2017-08-30 21:58
Here I created another [demo](http://www.andreaverlicchi.eu/lazyload/demos/callbacks_picture.html) to show that the script is calling the callback and setting the classes as expected.
I'm closing the issue - since it's not a bug - but don't worry, I'm still willing to help you (another message is coming right away).

**Closed by verlok** 2017-08-30 21:58 UTC
Labels: help wanted

**Comment by verlok** [comment] 2017-08-30 22:03
Hey, you're cheating! :) In the codepen you linked you're doing a very different thing from the one you were describing above: you're now using LazyLoad to set background images directly!

The answer to the fact that LazyLoad neither fires the callbacks nor sets the classes in this case is that it's impossible to do, since no event is fired by the browser when a background image has finished loading.

**Comment by verlok** [comment] 2017-08-30 22:08
@bitfella sorry, my mistake, I'm confusing the threads (it's late here and I'm out of coffee) with #120. You're not a cheater 👍 

Anyway my previous reply already answered your problem. It's just impossible to do with background images.

**Comment by verlok** [comment] 2017-08-30 22:10
@bitfella anyway, for the next time I suggest you to understand better what was the discussion before to state "I have the same problem", because @Hackintosh wasn't using background images.

**Comment by bitfella** [comment] 2017-08-30 22:12
I am sorry, I knew I was doing something wrong :)
Moreover I forgot to point out that I was using the script to load background images in my first comment. If i my give you and advice, I suggest to clearly declare this browser restriction (for background loading mode) in the docs (if it is not already there).

Thanks again
