### ISSUE TITLE
The "loading" class

### ISSUE THREAD

**Issue by mxaviers** [verlok/lazyload#44] opened 2016-12-06 06:44 UTC
The plugin works completely fine on my wordpress site when first opening a page, but I noticed that when it's refreshed, most of the time, the function will not complete and prevent the loading class from turning into "loaded". I didn't do much configuration to the plugin, but only have the data source pointed to "src" instead of "original".

**Comment by verlok** [comment] 2016-12-06 15:05
So the problem is that the class doesn't change from loading to loaded? Can you give me the URL of your website?

**Comment by mxaviers** [comment] 2016-12-06 16:29
Yes, only when it refreshes though. I did manage to find a workaround through jQuery which is probably not the best solution but it works for me. However, I did take it out for your inspection. The link is uat.lusitanialights.com/music. 

But I've also noticed that this plugin only recognizes JPG files, does it not do PNG?

**Comment by verlok** [comment] 2016-12-08 20:06
Thank you,
I'm gonna take a look at the link you provided.

But where did you read that my LazyLoad only supports JPG files? It supports everything it's loadable by the img tag, actually.

**Comment by verlok** [comment] 2016-12-08 20:10
I took a look. Are you talking about this single background image?

```html
<header class="bg_preloaded landing-page-image single-page" data-original="http://uat.lusitanialights.com/wp-content/uploads/2016/09/music-page-bg.jpg">
```

Since it's a background image, there is no way to listen to the "load" event for the image, so the `loaded` class cannot be added programmatically.

**Comment by mxaviers** [comment] 2016-12-08 20:36
Sorry, it was just an assumption about the PNG since the most of images that weren't being loaded were PNG. 

And actually, the header's background image is fine, it's the images in the content area, such as itunes and spotify icons in the right hand side and the album cover on the left.

**Comment by verlok** [comment] 2016-12-09 06:57
Ok, but I can't see any images in the page. I checked the source and there isn't any `img` tag with the `data-*` attribute set. And the images you mentioned aren't visible on the page. Something is missing, but I don't know why.

**Comment by mxaviers** [comment] 2016-12-09 08:47
Do you see a "loading" class on the img tags?
Because the images are going through the WordPress editor, do you know how to add the "data-original" attribute in the image tag without going into the text editor?

    On Thursday, December 8, 2016 11:57 PM, Andrea Verlicchi <notifications@github.com> wrote:
 

 Ok, but I can't see any images in the page. I checked the source and there isn't any img tag with the data-* attribute set. And the images you mentioned aren't visible on the page. Something is missing, but I don't know why.—

**Comment by verlok** [comment] 2016-12-09 08:59
> Do you see a "loading" class on the img tags?

Ok, taking a look at the DOM through the inspector, I see them. But looking at the html source of the page (cmd + alt + U on Chrome), I can see that the URL of the images are placed directly in the `src` attribute, and not via `data-something`...

```html
<img class="stream-i-img" src="http://uat.lusitanialights.com/wp-content/themes/lusitanialights/images/lusitania-icons-07.png" />
```

...so LazyLoad doesn't have anything to load, because this way the images are not lazily loaded, but are loaded directly by the browser when parsing the HTML of the page. What do you expect LazyLoad to do in this case?

> Do you know how to add the "data-original" attribute in the image tag without going into the text editor?

No I don't know, I'm sorry.

By the way I'm closing this issue because it's not a real issue.

**Closed by verlok** 2016-12-09 08:59 UTC
Labels: help wanted

**Comment by verlok** [comment] 2017-07-06 20:33
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
