### ISSUE TITLE
First Featured Image not Loading in Chrome

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#46] opened 2016-12-17 02:58 UTC
All other images are being loaded except the first image but it do works in Firefox and Safari

>[Check out This URL](https://yerl.org/4qPMBIuUDnRpPoR1ojLwlN)

**Comment by verlok** [comment] 2016-12-17 21:30
It looks like an untrustworthy URL to me. And your user looks fake too. Sorry, closing this issue. If you're human please prove it.

**Comment by marichelle** [comment] 2016-12-18 05:37
@verlok I also experienced this issue, but it happens to me in both Chrome v55 and Firefox v47 (I didn't test Safari). Note: I tested the plugin in a vanilla environment and that worked fine, but when I tried to run it in a more complex environment (JS using a module pattern), the Above The Fold images wouldn't show on page load, but upon the slightest scroll, the lazy load would trigger as expected.

**Comment by Niresh12495** [comment] 2016-12-18 06:19
How do you say this http://www.hackintosh.computer/190/enable-trim-on-macos/
url isn't trustworthy? closing the issue and tellin some one prove wtf?

**Comment by verlok** [comment] 2016-12-19 10:08
@Niresh12495 sorry about that, the URL wasn't the one you're reporting now, it was https://yerl.org/4qPMBIuUDnRpPoR1ojLwlN so very hard to trust. And I'm sorry, but your profile with 5 numbers and 4 forks looks like bot-generated too. Anyway your reply proved you're human to me. 👍

**Comment by verlok** [comment] 2016-12-19 10:16
@marichelle thank you very much for your description, now I get what the problem is.

I will fix this in the script itself, but if you need a quick fix, just call LazyLoad's `handleScroll` function.

For example, say you're initializing LazyLoad on document ready and assigning it to the `myLazyLoad` variable...

```js
document.addEventListener("DOMContentLoaded", function() { 
  var myLazyLoad = new LazyLoad({ /* options */ });
  myLazyLoad.handleScroll(); //this does the trick, calling LazyLoad's scroll handler without an actual scroll
});
```

**Comment by marichelle** [comment] 2016-12-19 20:10
@verlok Thanks for your response, but unfortunately `handleScroll()` didn't work for me.

**Comment by verlok** [comment] 2017-01-24 22:32
I'm testing it now on the [demo pages](http://verlok.github.io/lazyload/#demos) on Chrome 55 and I still can't see the problem. It probably occurs just when called using a JS module pattern, as @marichelle wrote above. I'll try and fix this too.

**Comment by verlok** [comment] 2017-01-24 22:38
@marichelle can you please repost the HTML and JS code you're using, so that I can do a better analysis? Thanks

**Comment by verlok** [comment] 2017-01-24 22:43
@Niresh12495 I visited your page using Chrome 55 but I didn't see the problem. Maybe you replaced my script with something else. Do you see the problem on the [demo pages](http://verlok.github.io/lazyload/#demos)?

**Comment by verlok** [comment] 2017-01-29 07:11
Is this still an issue?

**Closed** 2017-02-11 22:29 UTC

**Comment by sdthornton** [comment] 2018-10-03 15:15
Just a heads up, it is still an issue as of 10/3/18. Seems like it's any above-the-fold images on first load in Chrome only.

**Comment by sdthornton** [comment] 2018-10-03 15:15
Also, doesn't seem to be an issue when running dev server.

**Comment by verlok** [comment] 2018-10-03 16:03
@sdthornton I was never able to reproduce this issue and I can’t figure out how to do that. 

Are you able to reproduce the problem in any of the demo pages (see the `demos` folder)?

@marichelle, @Niresh12495 are you still experiencing this?

**Comment by krepky** [comment] 2018-12-02 19:59
Similar problem. The console does not report any failures (i can only say that Date.now () refuses to see the first image).
`handleScroll()` didn't work for me too. I found out that the picture is loaded if you assign a width to it, so this small trick somehow solves the problem:
```
$('.stills').eq(0).css('width','1px');
function loadfirstimg(){$('.stills').eq(0).css('width','auto');}setTimeout(loadfirstimg, 10);
```
This bug lives in Chrome only. I also use webp image add-on ("to_webp: true"), content is loaded using ajax.

**Comment by verlok** [comment] 2019-02-23 13:28
Few changes with version 11.0.0 just released.
`handleScroll()` doesn't exist anymore.
If you still need help, please reproduce the issue on [codepen](https://codepen.io) and I will be able to help you.
Thanks
