### ISSUE TITLE
Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by delideha** [verlok/lazyload#155] opened 2017-11-20 19:49 UTC
Hi, I'm fronting this issue. my img tags are like below.

`<img src="/sites/veganbahcesi/layouts//images/loader.gif" class="lazy img-responsive" data-src="/sites/veganbahcesi/uploads/products/4/medium/06cabb41c30e355ae3fa6e2365c6c1ad.jpg" alt="Vegan Sade Tost">`

**the error is on console :** 
Uncaught TypeError: Cannot read property 'tagName' of null
    at setSourcesForPicture (lazyload.js:65)
    at setSources (lazyload.js:85)
    at revealElement (lazyload.js:163)
    at lazyload.js:187
    at Array.forEach (<anonymous>)
    at IntersectionObserver.onIntersection (lazyload.js:184)

i found solution by editing lazyload.js  line 65 

from this 

```js
	        if (parent.tagName !== "PICTURE") {
		        return;
	        }
	        for (var i = 0, pictureChild; pictureChild = parent.children[i]; i += 1) {
		        if (pictureChild.tagName === "SOURCE") {
			        var sourceSrcset = getData(pictureChild, dataSrcSet);
			        if (sourceSrcset) {
				        pictureChild.setAttribute("srcset", sourceSrcset);
			        }
		        }
	        }
```
    
to this : 
```js
        if(parent) {
	        if (parent.tagName !== "PICTURE") {
		        return;
	        }
	        for (var i = 0, pictureChild; pictureChild = parent.children[i]; i += 1) {
		        if (pictureChild.tagName === "SOURCE") {
			        var sourceSrcset = getData(pictureChild, dataSrcSet);
			        if (sourceSrcset) {
				        pictureChild.setAttribute("srcset", sourceSrcset);
			        }
		        }
	        }
        }
```

**Comment by verlok** [comment] 2017-11-20 20:36
Hi there, 
could you tell me in what browser and version you get the error?

Also, could you post the HTML code of the `img`'s container? It's kinda strange that your `img` tags don't have a parent element, right? It should be `body`, ad least.

**Comment by verlok** [comment] 2017-11-20 20:53
I tried different cases but never found one where an `img`'s `parentElement` could be null.
The only case would be when you create an `img` but you don't attach it to the DOM ([see here](Have a look here, https://codepen.io/verlok/pen/wPyXXR?editors=0010 )). 
But in this case, I can't see how LazyLoad could be useful.

**Comment by verlok** [comment] 2017-11-24 06:18
@delideha did you solve?

**Comment by delideha** [comment] 2017-11-24 11:03
Yeapp, it seems working fine. Thanks 😊.

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

________________________________
Gönderen: Andrea Verlicchi <notifications@github.com>
Gönderildi: Friday, November 24, 2017 9:18:27 AM
Kime: verlok/lazyload
Bilgi: Gökhan Özergen; Mention
Konu: Re: [verlok/lazyload] Cannot read property 'tagName' of null (#155)


@delideha<https://github.com/delideha> did you solve?

**Comment by Tabrisrp** [comment] 2017-12-22 19:47
I seem to still have this error showing on some websites, with 10.3.5, but only on Chrome.

It doesn't seem to prevent the script from working either, since I can see the src correctly set and the class `lazyloaded` added.

I'm reporting it but I have no idea with it's triggering. I could give you the HTML if you'd like to have a look.

**Comment by verlok** [comment] 2017-12-25 06:49
Yes please, the parts of HTML and JS related to LazyLoad (your images and the LazyLoad initialization). 
Thanks

**Comment by verlok** [comment] 2018-01-05 05:20
@tabrisp, you there?

**Comment by verlok** [comment] 2018-01-05 05:21
@tabrisrp, you there?

**Comment by Tabrisrp** [comment] 2018-01-05 19:57
Sorry I was on holidays.

This is only happening on one specific page of this customer WordPress website, so I'm pretty sure it's some kind of conflict with another plugin or his theme, it's not really worth the time.

You can re-close this 👍

**Comment by verlok** [comment] 2018-01-05 22:25
Thanks

**Comment by dhunink** [comment] 2018-03-10 18:49
Hi!

Just stumbled upon the exact same issue. It is indeed a WordPress website. It's an issue that's only related to Chrome.
Here's an example page where the error pops-up: https://ghana-car-rentals.com/country-info/.
But: just by the looks of it, the error only appears once every two or three times the page is loaded. Could this be a matter of timing, where parts of the DOM have not rendered in full yet?

**Comment by verlok** [comment] 2018-03-12 05:02
HI @dhunink,
thanks for reporting this. 

You’re using the latest version/s of LazyLoad, right? I guess so.

This error might be caused by Wordpress removing some DOM from the page. My script then reads the property tagName from the image element and its parent, but the element became null for some reason. 

We can fix the script checking that the image is still existing (not null), but I would like to understand the reason of the bug first. 

Did you already do some debugging on your webpage code?

**Comment by verlok** [comment] 2018-03-21 17:01
I'd advice you to AVOID using LazyLoad on the images in the slider, because LazyLoad only works in actual scroll containers, and it doesn't affect sliders since they don't do actual scrolling but they move objects (typically images) instead.

You should use Revolution Slider's LazyLoad option.

That said, I will integrate your fix that checks `parent`, which would solve the javascript error, but it wouldn't make sliders to load images lazily.

**Comment by dhunink** [comment] 2018-03-22 15:26
@verlok I totally understand way LazyLoad should not be used on a slider, as the way a slider works is different from the way LazyLoad is intended to respond to images slipping into the viewport. Using Revolution Slider's own LazyLoad function is indeed something I try to use whenever I can. 

However, that doesn't fix the error thrown by this LazyLoad script. Isn't there a way to somehow find out if an image is actually visible to the user (instead or combined with using the `parent` fix) to avoid falsely applied LazyLoad? 

Personally I'm not including LazyLoad myself, but I'm using the WP Rocket caching plugin, in which your LazyLoad script is incorporated. So I don't have any control over wether or not Lazyload is applied on certain images. I can think of many scenario's where users would benefit from a solution in which the LazyLoad script performs a simple check on an element to see if it is actually a image and has attributes as expected. Does that make any sense to you as well?

**Comment by verlok** [comment] 2018-03-27 21:05
I've checked and I saw that the current version of WP Rocket does NOT use my LazyLoad. See the [LazyLoad page of WP Rocked documentation](https://github.com/wp-media/wp-rocket/blob/0d60c8e91e916a5652fc3607b13ee411a85e4839/inc/front/js/lazyload-1.0.5.js)
Are you sure that the problem is with my script?

**Comment by verlok** [comment] 2018-03-27 21:18
I've added the check in 10.5.2 so your problem should be solved.

**Closed by verlok** 2018-03-27 21:18 UTC
