### ISSUE TITLE
Using LazyLoad with Facebook Video (Iframe)

### ISSUE THREAD

**Issue by wamk9** [verlok/lazyload#410] opened 2020-01-19 21:35 UTC
I'm developing a website focusing at pagespeed, the homepage use a repository created by me (ModernizeImage) with a dependence of Verlok's LazyLoad (i'm using 12.0.3 in this website) to verify compatibility with Jpg/WebP, and both repositories works fine...

But the client ask to insert some Facebook Videos at homepage and now we have 8mb~ and load finish after 20secs~ (before has 500kb ~ and load in 2~3secs).

I try to use the lazyload on iframe (working directly, without my repository), but stay loading all Facebook files and after a scroll the page, the callback of Verlok's LazyLoad show ENTERED and  REVEALED (?)

My question is, why this happens? I'm think this is more about Facebook and i have some solutions, but i want to do something more "standard" to use in many other projects.

And of course, website's link is [nathanafernandes.com.br](https://nathanafernandes.com.br/?utm_source=verlok-lazyload&utm_medium=github&utm_campaign=dev)

**Comment by verlok** [comment] 2020-01-30 09:27
Ola Wesley, tudo bem? (morei no Brasil entao eu falo Portugues).
I can't understand what you are asking here. You don't understand why my script throws both the ENTERED and REVEALED callbacks?
Could you please reproduce and isolate the problem in a Pen on [Codepen](https://codepen.io)?
Thanks

**Comment by verlok** [comment] 2020-01-30 09:29
Uh I guess I understood what might be your problem. Did you set a minimum height for the iframes? If you didn't, they probably appear to be all inside the viewport at the first scroll.

**Comment by verlok** [comment] 2020-02-28 09:59
I'm closing this since you didn't answer my questions so I assume you solved the issues.
If you still need help, feel free to reopen this (and answer my questions, hehe).

**Closed by verlok** 2020-02-28 09:59 UTC
Labels: TYPE: Question
